[general]
max_message_sender_threads = 2
max_frame_processor_threads = 2
min_aggregation_frames_threshold = 3
max_frame_buffers = 10
local_timezone = "Europe/Amsterdam"
timestamp_format = "%Y-%m-%d, %H:%M:%S %Z"
mute_img_send_minutes = 10

[logging]
log_base_folder = "/var/log/balrog-logs"
log_file_name = "cat_logger.log"
log_dbg_file_name = "cat_logger-dbg.log"
stdout_debug_level = "INFO"
enable_cascade_logging = false
enable_circular_buffer_logging = false
max_log_file_size_mb = 500
max_log_files_kept = 2

[camera]
camera_fps = 10
camera_cleanup_frames_threshold = 60

[model]
event_reset_threshold = 6
cat_counter_threshold = 6
cumulus_prey_threshold = -10
cumulus_no_prey_threshold = 2.9603
prey_val_hard_threshold = 0.6

[flap]
let_in_open_seconds = 40
