[general]
max_message_sender_threads = 2
max_frame_processor_threads = 1
min_aggregation_frames_threshold = 3
max_frame_buffers = 100

[camera]
camera_fps = 10
camera_cleanup_frames_threshold = 60

[model]
event_reset_threshold = 6
cat_counter_threshold = 6
cumulus_prey_threshold = -10
cumulus_no_prey_threshold = 2.9603
prey_val_hard_threshold = 0.6

[flap]
let_in_open_seconds = 40